# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sortllr <- function(Xmat, mb, numUpdates = 5L, family = "laplace", df = 10) {
    .Call(`_scorelingam_sortllr`, Xmat, mb, numUpdates, family, df)
}

getWeights <- function(X, pa) {
    .Call(`_scorelingam_getWeights`, X, pa)
}

corrMat <- function(Xmat) {
    .Call(`_scorelingam_corrMat`, Xmat)
}

getResids <- function(X, B) {
    .Call(`_scorelingam_getResids`, X, B)
}

getRsq <- function(X, B) {
    .Call(`_scorelingam_getRsq`, X, B)
}

