# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scorelingam_ <- function(Xmat, mb, numUpdates = 5L, family = "laplace", df = 10) {
    .Call(`_scorelingam_scorelingam_`, Xmat, mb, numUpdates, family, df)
}

getWeights_ <- function(X, pa) {
    .Call(`_scorelingam_getWeights_`, X, pa)
}

corrMat_ <- function(Xmat) {
    .Call(`_scorelingam_corrMat_`, Xmat)
}

